### ISSUE TITLE
NPM ERROR

### ISSUE THREAD

**Issue by apricat** [sbstjn/noduino#10]
Hi, I'm having issues with the npm configuration...

gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:350:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:96:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:678:10)
gyp ERR! System Darwin 12.2.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Clobot/noduino/node_modules/serialport
gyp ERR! node -v v0.8.12
gyp ERR! node-gyp -v v0.7.0
gyp ERR! not ok 
npm ERR! serialport@1.0.8 install: `node-gyp rebuild`
npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR! 
npm ERR! Failed at the serialport@1.0.8 install script.
npm ERR! This is most likely a problem with the serialport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls serialport
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 12.2.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/Clobot/noduino
npm ERR! node -v v0.8.12
npm ERR! npm -v 1.1.63
npm ERR! code ELIFECYCLE
[ws v0.4.22] Native code compile failed (but the module will still work):
[ws v0.4.22] The native extensions are faster, but not required.
[ws v0.4.22] On Windows, native extensions require Visual Studio and Python.
[ws v0.4.22] On Unix, native extensions require Python, make and a C++ compiler.
[ws v0.4.22] Start npm with --ws:verbose to show compilation output (if any).
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/Clobot/noduino/npm-debug.log
npm ERR! not ok code 0

/----------------------
npm ERR! This is most likely a problem with the serialport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
/----------------------

Any fix?
Thank you!

**Comment by borntodive** [comment]
Same error here on windows and MacOs X.....Did some one fixed it?

Thankssss

**Comment by sbstjn** [comment]
Seems to be a problem with installign `node-serialport`:

```
npm ERR! Failed at the serialport@1.0.8 install script.
npm ERR! This is most likely a problem with the serialport package,
```

**Comment by glidej** [comment]
I had this issue and found out I didn't have GCC installed. I installed GCC [separately](https://developer.apple.com/downloads/index.action?=Command Line Tools %28OS X Mountain Lion%29) to avoid having to download the whole Xcode package and I was able to install successfully afterwards.

**Comment by carlituxman** [comment]
install xcode comand line tools

Preferences... > Downloads > Command Line Tools

**Comment by bengarvey** [comment]
@carlituxman perfect.  Thanks, that worked in OSX.

**Comment by kluplau** [comment]
Do we have a fix for Windows users? I am on Windows 8.1 Pro, and faces the exact same issue.

**Comment by glidej** [comment]
@Blueblau I'm not familiar with the Windows environment, but it appears this issue stems from not having GCC installed. A quick google for "windows gcc" reveals [this](http://www.mingw.org/category/wiki/download) project. I would give that a try.

**Comment by kluplau** [comment]
Thanks. 

The mentioned issue resolved itself when I installed Python. But then I had trouble making the command "python" global. I still haven't found a solution to this, so I am on the verge of quitting.
