### ISSUE TITLE
How do I access the examples?

### ISSUE THREAD

**Issue by joshuamcginnis** [sbstjn/noduino#23]
Seems like it should be really easy, but I'm finding it confusing. How the heck do I access the examples?

It also isn't clear what needs to be running in order for the examples to work. Does srv.web.js need to be listening whilst srv.app.js is also running? I'm not sure.

I've tried:

``` bash
node srv.web.js
info  - socket.io started
Listening on http://localhost:8080

http://localhost:8080/examples/walkLED.html //404
```

and this:

```
node srv.app.js

define(['kickstart', 'module', 'path', 'fs'], function (kickstart, module, pat
^
ReferenceError: define is not defined
    at Object.<anonymous> (/Users/me/sandbox/node-js-projects/noduino/srv.app.js:11:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3
```

**Comment by nick-anykeydesigns** [comment]
First run "node srv.web.js"

Then using your web browser go to http://localhost:8080
