### ISSUE TITLE
express.compiler undefined

### ISSUE THREAD

**Issue by ktiedt** [sbstjn/noduino#4]
When trying to run srv.web.js from your tutorial I get this error: (Note: I got to this error _AFTER_ I installed express explcitly, since it wasnt listed as a requirement in sub modules or otherwise -- the error stems from line 8 of kickstart -- and I have been unable to find any solutions to this on the web.

express.compiler.compilers.less.compile = function (str, fn) {

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Calling node's require("kickstart") failed with error: TypeError: Cannot read property 'compilers' of undefined
    at /Users/ktiedt/repos-git/noduino/node_modules/requirejs/bin/r.js:2255:27
    at Object.execCb (/Users/ktiedt/repos-git/noduino/node_modules/requirejs/bin/r.js:1766:33)
    at Object.check (/Users/ktiedt/repos-git/noduino/node_modules/requirejs/bin/r.js:1075:51)
    at Object.enable (/Users/ktiedt/repos-git/noduino/node_modules/requirejs/bin/r.js:1316:22)
    at Object.init (/Users/ktiedt/repos-git/noduino/node_modules/requirejs/bin/r.js:974:26)
    at callGetModule (/Users/ktiedt/repos-git/noduino/node_modules/requirejs/bin/r.js:1341:59)
    at Object.completeLoad (/Users/ktiedt/repos-git/noduino/node_modules/requirejs/bin/r.js:1641:21)
    at Function.load (/Users/ktiedt/repos-git/noduino/node_modules/requirejs/bin/r.js:2265:17)
    at Object.load (/Users/ktiedt/repos-git/noduino/node_modules/requirejs/bin/r.js:1755:21)
    at Object.load (/Users/ktiedt/repos-git/noduino/node_modules/requirejs/bin/r.js:1032:29)

**Comment by sbstjn** [comment]
I just had the same error in some other project. Seems to happen when using [express](http://expressjs.com) version 3.0.0 beta (latest pointer in npm is on beta). I'll update the package.json file to use express 2.5.x…

Maybe a `npm install express@2.5.11` will fix your problem?

**Comment by ktiedt** [comment]
This got farther.. 

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Calling node's require("socket.io") failed with error: Error: Cannot find module 'uglify-js'
    at /Users/ktiedt/repos-git/noduino/node_modules/requirejs/bin/r.js:2255:27
    at Object.execCb (/Users/ktiedt/repos-git/noduino/node_modules/requirejs/bin/r.js:1766:33)
    at Object.check (/Users/ktiedt/repos-git/noduino/node_modules/requirejs/bin/r.js:1075:51)
    at Object.enable (/Users/ktiedt/repos-git/noduino/node_modules/requirejs/bin/r.js:1316:22)
    at Object.init (/Users/ktiedt/repos-git/noduino/node_modules/requirejs/bin/r.js:974:26)
    at callGetModule (/Users/ktiedt/repos-git/noduino/node_modules/requirejs/bin/r.js:1341:59)
    at Object.completeLoad (/Users/ktiedt/repos-git/noduino/node_modules/requirejs/bin/r.js:1641:21)
    at Function.load (/Users/ktiedt/repos-git/noduino/node_modules/requirejs/bin/r.js:2265:17)
    at Object.load (/Users/ktiedt/repos-git/noduino/node_modules/requirejs/bin/r.js:1755:21)
    at Object.load (/Users/ktiedt/repos-git/noduino/node_modules/requirejs/bin/r.js:1032:29)

**Comment by sbstjn** [comment]
which node version do you use?

**Comment by ktiedt** [comment]
currently on 0.6.14

**Comment by sbstjn** [comment]
I'm using v0.6.19 and the following package versions:

`npm install colors@0.6.0-1 serialport@1.0.0 kickstart@0.0.6 requirejs@2.0.4 socket.io@0.9.6`

**Comment by ktiedt** [comment]
Just checked, those are the same versions installed, it appears a submodule has a bad dependency list... I updated node... to eliminate that potential problem then ended up having to run:
npm install uglify-js
this resolved the above error... then
npm install active-x-obfuscator
to resolve:
/Users/ktiedt/repos-git/noduino/node_modules/requirejs/bin/r.js:1902
        throw err;
              ^
Error: Calling node's require("socket.io") failed with error: Error: Cannot find module 'active-x-obfuscator'
    at req.load (/Users/ktiedt/repos-git/noduino/node_modules/requirejs/bin/r.js:2255:27)
    at Object.context.execCb (/Users/ktiedt/repos-git/noduino/node_modules/requirejs/bin/r.js:1766:33)
    at Object.Module.check (/Users/ktiedt/repos-git/noduino/node_modules/requirejs/bin/r.js:1075:51)
    at Object.Module.enable (/Users/ktiedt/repos-git/noduino/node_modules/requirejs/bin/r.js:1316:22)
    at Object.Module.init (/Users/ktiedt/repos-git/noduino/node_modules/requirejs/bin/r.js:974:26)
    at callGetModule (/Users/ktiedt/repos-git/noduino/node_modules/requirejs/bin/r.js:1341:59)
    at Object.context.completeLoad (/Users/ktiedt/repos-git/noduino/node_modules/requirejs/bin/r.js:1641:21)
    at Function.req.load (/Users/ktiedt/repos-git/noduino/node_modules/requirejs/bin/r.js:2265:17)
    at Object.context.load (/Users/ktiedt/repos-git/noduino/node_modules/requirejs/bin/r.js:1755:21)
    at Object.Module.load (/Users/ktiedt/repos-git/noduino/node_modules/requirejs/bin/r.js:1032:29)

So likely not a problem with noduino other than it depends on a project with bad dependencies?

**Comment by sbstjn** [comment]
Try downgrading to a lower version of `uglify-js` or `active-x-obfuscator`, see `npm info uglify-js` for a version history…

**Comment by ktiedt** [comment]
Once I install those (no version specifics) -- srv.web.js starts, just the demo pages "Connect to" all cause a segfault (I dont have the board setup with ledWalker yet -- since I couldnt even get the code to run -- setting up a board now to test)
