### ISSUE TITLE
EventEmitter undefined Error

### ISSUE THREAD

**Issue by sherlockholmes** [sbstjn/noduino#5]
Hi, 

When I try to run " node srv.web.js", showme  that error.

/noduino/node_modules/requirejs/bin/r.js:1902
        throw err;
              ^
Error: Evaluating duino/lib/board.js as module "duino/lib/board.js" failed with error: TypeError: Cannot read property 'EventEmitter' of undefined
    at Function.req.load (/noduino/node_modules/requirejs/bin/r.js:2243:23)
    at Object.context.load (/noduino/node_modules/requirejs/bin/r.js:1755:21)
    at Object.Module.load (/noduino/node_modules/requirejs/bin/r.js:1032:29)
    at Object.Module.fetch(/noduino/node_modules/requirejs/bin/r.js:1022:66)
    at Object.Module.check (/noduinonode_modules/requirejs/bin/r.js:1054:26)
    at Object.Module.enable (/noduino/node_modules/requirejs/bin/r.js:1316:22)
    at Object.context.enable (/noduino/node_modules/requirejs/bin/r.js:1608:39)
    at Object.Module.enable.mod (/noduino/node_modules/requirejs/bin/r.js:1301:33)
    at g (/noduino/node_modules/requirejs/bin/r.js:234:23)
    at each (/noduino/node_modules/requirejs/bin/r.js:163:31)

What you think about it? 

Helpme pls, I'm new whit nodeJS xD

**Comment by rounaksingh** [comment]
hey i m also receiving this error ......although i installed noduino & sub-modules, explicitly, more than two times..I m running node.js 0.6.6......plz help semu

**Comment by mysterlune** [comment]
i'm getting this error, too.  just trying to fire up the test.blinkLED.js example.  

if you're getting this error when starting srv.web.js, take a look at the call to require duino's board.js module in:

noduino/public/scripts/libs/Noduino.Serial.js 

... around line 42:

```
var Board = require('../../duino/lib/board.js');
```

... is expecting duino to be installed in a specific location.  it seems that this relative path is correct if you are running the tests in "examples", but it's wrong if you're starting a server in the main directory.  

try removing one of the "../" from the path, then try to start srv.web.js

**Comment by rounaksingh** [comment]
thanks for suggestion mysterlune............i am going to try it........

**Comment by hugocruz** [comment]
mysterlune, that did it.
