### ISSUE TITLE
define is not defined

### ISSUE THREAD

**Issue by j-5-s** [sbstjn/noduino#7]
Trying to get started following the basic install however when executing

``` text
node srv.app.js
```

im getting 

``` text
/Users/james/Developer/arduino/noduino/srv.app.js:11
define(['kickstart', 'module', 'path', 'fs'], function (kickstart, module, pat
^
ReferenceError: define is not defined
    at Object.<anonymous> (/Users/james/Developer/arduino/noduino/srv.app.js:11:1)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
```

I tried installing requirejs as a global but that did not work.  Also, what is the reason requirejs is being used on the server rather than using nodes built in module loader:

``` text
var x = require('./example');
```

Also, im using node v0.8.11

**Comment by j-5-s** [comment]
okay, i got it. main app is src.web.js.  Absolutely incredible!
